# Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  flickr30k:
    # data_dir: ${env.data_dir}/datasets
    data_type: images

    build_info:
      annotations:
        train:
          #url: https://storage.googleapis.com/sfr-vision-language-research/datasets/flickr30k_train.json
          storage: /content/drive/MyDrive/Ahmed/annotation_in_arabic/Arabic_train.json
        val:
          #url: https://storage.googleapis.com/sfr-vision-language-research/datasets/flickr30k_val.json
          storage: /content/drive/MyDrive/Ahmed/annotation_in_arabic/Arabic_val.json
        test:
          #url: https://storage.googleapis.com/sfr-vision-language-research/datasets/flickr30k_test.json
          storage: /content/drive/MyDrive/Ahmed/annotation_in_arabic/Arabic_test.json
      images:
          storage: /content/flicker30k/images
          # storage: /export/share/datasets/vision/flickr30k
